env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://host.docker.internal:5173
  parameters:
    failOnError: true
    progressToStdout: true
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 3
    url: http://host.docker.internal:5173
  type: spider
- parameters:
    maxDuration: 3
    url: http://host.docker.internal:5173
  type: spiderAjax
- parameters:
    maxDuration: 15
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: results/zap/frontend/report.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: results/zap/frontend/report.md
    reportTitle: ZAP Scanning Report
    template: traditional-md
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: results/zap/frontend/report.xml
    reportTitle: ZAP Scanning Report
    template: traditional-xml
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: results/zap/frontend/report.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
